"""Changes in game and match tables

Revision ID: 0002
Revises: 0001
Create Date: 2024-08-26 11:08:07.178072

"""

import logging

from alembic import op
import sqlalchemy as sa
from backend.migrations.versions import log


# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "all_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_all_events"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("match_id", sa.Integer(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum("BALL_POTTED", "FOUL", "TURN_END", "GAME_WIN", name="eventtype"),
            nullable=True,
        ),
        sa.Column("ball_number", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name="fk_games_id_events"),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name="fk_matches_id_events"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name="fk_players_id_events"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("match_actions")
    with op.batch_alter_table("clubs", schema=None) as batch_op:
        batch_op.alter_column("table_count", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("games_played", existing_type=sa.INTEGER(), nullable=True)
    try:
        log.info(f"{revision} - Altering table 'games'...")
        with op.batch_alter_table("games", schema=None) as batch_op:
            batch_op.add_column(sa.Column("club_id", sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column("season_id", sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column("tournament_id", sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column("round_number", sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column("player1_score", sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column("player2_score", sa.Integer(), nullable=True))
            batch_op.add_column(
                sa.Column(
                    "status",
                    sa.Enum("IN_PROGRESS", "COMPLETED", name="gamestatus"),
                    nullable=True,
                )
            )
            batch_op.drop_constraint("fk_games_match_id", type_="foreignkey")
            batch_op.create_foreign_key(
                "fk_tournament_id_games", "tournaments", ["tournament_id"], ["id"]
            )
            batch_op.create_foreign_key(
                "fk_clubs_id_games", "clubs", ["club_id"], ["id"]
            )
            batch_op.create_foreign_key(
                "fk_season_id_games", "season", ["season_id"], ["id"]
            )
            batch_op.drop_column("match_id")
    except Exception as e:
        log.error(f"{revision} - Error altering table 'matches'. message: {e}")
    try:
        log.info(f"{revision} - Altering table 'matches'...")
        with op.batch_alter_table("matches", schema=None) as batch_op:
            batch_op.add_column(sa.Column("game_id", sa.Integer(), nullable=False))
            batch_op.add_column(
                sa.Column(
                    "status",
                    sa.Enum("IN_PROGRESS", "COMPLETED", name="matchstatus"),
                    nullable=True,
                )
            )
            batch_op.drop_constraint("fk_matches_tournament_id", type_="foreignkey")
            batch_op.create_foreign_key(
                "fk_game_id_matches", "games", ["game_id"], ["id"]
            )
            batch_op.drop_column("round_number")
            batch_op.drop_column("tournament_id")
    except Exception as e:
        log.error(f"{revision} - Error altering table 'matches'. message: {e}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tournament_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("round_number", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_matches_tournament_id", "tournaments", ["tournament_id"], ["id"]
        )
        batch_op.drop_column("status")
        batch_op.drop_column("game_id")

    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.add_column(sa.Column("match_id", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_games_match_id", "matches", ["match_id"], ["id"]
        )
        batch_op.drop_column("status")
        batch_op.drop_column("player2_score")
        batch_op.drop_column("player1_score")
        batch_op.drop_column("round_number")
        batch_op.drop_column("tournament_id")
        batch_op.drop_column("season_id")
        batch_op.drop_column("club_id")

    with op.batch_alter_table("clubs", schema=None) as batch_op:
        batch_op.alter_column(
            "games_played", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("table_count", existing_type=sa.INTEGER(), nullable=False)

    op.create_table(
        "match_actions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("game_id", sa.INTEGER(), nullable=False),
        sa.Column("action_number", sa.INTEGER(), nullable=False),
        sa.Column("player_id", sa.INTEGER(), nullable=True),
        sa.Column("ball_color", sa.VARCHAR(length=6), nullable=True),
        sa.Column("target_pocket", sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name="fk_match_actions_game_id"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name="fk_match_actions_player_id"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_match_actions"),
    )
    op.drop_table("events")
    op.drop_table("all_events")
    # ### end Alembic commands ###
