"""Change model News

Revision ID: 0003
Revises: 0002
Create Date: 2024-08-11 21:04:13.563740

"""

from backend.migrations.versions import log

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    log.info(f"{revision} -  Drop column source_id in table 'news'")
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.drop_column("source_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    log.info(f"{revision} - Return table column source_id to news")
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_id", sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
