"""Add season is_active field

Revision ID: 0004
Revises: 0003
Create Date: 2024-08-18 20:28:23.692471

"""

from backend.migrations.versions import log

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game", schema=None) as batch_op:
        log.info(f"{revision} - Add column 'is_finished' to 'game' table")
        batch_op.add_column(sa.Column("is_finished", sa.Boolean(), nullable=True))

    with op.batch_alter_table("season", schema=None) as batch_op:
        log.info(f"{revision} - Add column 'is_active' to 'season' table")
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("season", schema=None) as batch_op:
        log.info(f"{revision} - Drop column 'is_finished' from 'game' table")
        batch_op.drop_column("is_active")

    with op.batch_alter_table("game", schema=None) as batch_op:
        log.info(f"{revision} - Drop column 'is_active' from 'season' table")
        batch_op.drop_column("is_finished")

    # ### end Alembic commands ###
