"""Prepare for RBAC system

Revision ID: 0006
Revises: 0005
Create Date: 2024-08-05 08:24:45.878696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party')
    op.drop_table('party_event')
    op.drop_table('clubs')
    op.drop_table('party_type')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('played_games', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_player_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('notes')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('name')
        batch_op.drop_column('email')
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_player_user', type_='foreignkey')
        batch_op.drop_column('score')
        batch_op.drop_column('played_games')
        batch_op.drop_column('user_id')

    op.create_table('party_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clubs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('party_id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ball_number', sa.INTEGER(), nullable=True),
    sa.Column('event_time', sa.DATETIME(), nullable=False),
    sa.Column('details', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('type_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('winner_id', sa.INTEGER(), nullable=True),
    sa.Column('win_reason_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['party_type.id'], ),
    sa.ForeignKeyConstraint(['win_reason_id'], ['win_reason.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
